### ISSUE TITLE
Disable protonup

### ISSUE THREAD

**Issue by yochananmarqos** [topgrade-rs/topgrade#30]
## What did you expect to happen?
Nothing, since I already have GE-Proton7-37 installed.

## What actually happened?
It tried to download the same version and failed. It appears to be an unresolved upstream issue: 

https://github.com/AUNaseef/protonup/issues/25
https://github.com/AUNaseef/protonup/issues/37

## Additional Details
- Which operating system or Linux distribution are you using?
Manjaro (unstable branch)
- How did you install Topgrade?
My Manjaro PKGBUILD
- Which version are you running? 
Topgrade 9.1.0

<details>

<pre>
2022-10-17T22:07:03.196Z DEBUG topgrade_rs::runner          > Step "protonup"
 2022-10-17T22:07:03.196Z DEBUG topgrade_rs::utils           > Detected "/usr/bin/protonup" as "protonup"

―― 16:07:03 - protonup ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-10-17T22:07:03.196Z DEBUG topgrade_rs::executor        > Running "/usr/bin/protonup"
Ready to download Proton-GE-Proton7-37 
Size      : 397.0 MiB 
Published : 2022-10-05
Continue? (Y/n): 
Downloaded 100.00% - 397.1 MiB / 397.0 MiB   
Traceback (most recent call last):
  File "/usr/bin/protonup", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/protonup/__init__.py", line 4, in main
    return main()
  File "/usr/lib/python3.10/site-packages/protonup/cli.py", line 33, in main
    get_proton(version=args.tag, yes=args.yes, dl_only=args.download,
  File "/usr/lib/python3.10/site-packages/protonup/api.py", line 151, in get_proton
    tarfile.open(destination, "r:gz").extractall(install_directory())
  File "/usr/lib/python3.10/tarfile.py", line 2059, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.10/tarfile.py", line 2100, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.10/tarfile.py", line 2173, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.10/tarfile.py", line 2214, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/home/yochanan/.steam/root/compatibilitytools.d/GE-Proton7-37/files/lib64/wine/vkd3d-proton/libvkd3d-proton-utils-3.dll'
 2022-10-17T22:07:18.685Z DEBUG topgrade_rs::runner          > Step "protonup" failed: exit status: 1
 2022-10-17T22:07:18.685Z DEBUG topgrade_rs::terminal        > Desktop notification: protonup failed

</pre>
</details>

Please disable functionality for now until upstream resolves the issue.

**Comment by yochananmarqos** [comment]
It works with [protonup-ng](https://github.com/cloudishBenne/protonup-ng), see https://github.com/AUNaseef/protonup/pull/26

```
 2022-10-17T22:28:46.156Z DEBUG topgrade_rs::utils           > Detected "/usr/bin/protonup" as "protonup"

―― 16:28:46 - protonup ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-10-17T22:28:46.156Z DEBUG topgrade_rs::executor        > Running "/usr/bin/protonup"
[INFO] GE-Proton7-37 already installed
 2022-10-17T22:28:47.108Z DEBUG topgrade_rs::runner          > Step "pihole"
 2022-10-17T22:28:47.108Z DEBUG topgrade_rs::runner          > Step "Firmware upgrades"
 2022-10-17T22:28:47.108Z DEBUG topgrade_rs::utils           > Detected "/usr/bin/fwupdmgr" as "fwupdmgr"
 2022-10-17T22:28:47.108Z TRACE topgrade_rs::executor        > Output of "uname" "-r": Output { status: ExitStatus(unix_wait_status(0)), stdout: "6.0.2-3-MANJARO\n", stderr: "" }
 2022-10-17T22:28:47.108Z DEBUG topgrade_rs::steps::os::linux > Uname output: 6.0.2-3-MANJARO
```
