### ISSUE TITLE
Updating oh my zsh triggers failed debug assert

### ISSUE THREAD

**Issue by westernwontons** [topgrade-rs/topgrade#73]
## What did you expect to happen?
A successful update

## What actually happened?
There's a `debug_assert!()` call in `src/steps/git.rs:311:9` that fails on popping `$HOME/.oh-my-zsh` from the repositories HashSet. I added a couple debug assert's to determine which path causes the panic:
```
[src/steps/git.rs:309] "{:#?}" = "{:#?}"
[src/steps/git.rs:309] &self.repositories = {
    "/Users/nagybotond/.omzcustom/plugins/evalcache",
    "/Users/nagybotond/.omzcustom/plugins/msfvenom",
    "/Users/nagybotond/.dotfiles",
    "/Users/nagybotond/.omzcustom/plugins/zsh-autosuggestions",
}
[src/steps/git.rs:310] "{:#?}" = "{:#?}"

this one >>>>> [src/steps/git.rs:310] path = "/Users/nagybotond/.oh-my-zsh"

thread 'main' panicked at 'assertion failed: _removed', src/steps/git.rs:311:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:115:5
   3: topgrade::steps::git::Repositories::remove
             at ./src/steps/git.rs:311:9
   4: topgrade::steps::zsh::run_oh_my_zsh
             at ./src/steps/zsh.rs:161:5
   5: topgrade::run::{{closure}}
             at ./src/main.rs:289:53
   6: topgrade::runner::Runner::execute
             at ./src/runner.rs:37:19
   7: topgrade::run
             at ./src/main.rs:289:9
   8: topgrade::main
             at ./src/main.rs:489:11
   9: core::ops::function::FnOnce::call_once
             at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Additional Details
- Which operating system or Linux distribution are you using?
MacOS 13.0
- How did you install Topgrade?
`cargo install topgrade` at first, then I realised it's unmaintained and I ended up here, so I installed it from this repo's main branch
- Which version are you running? 
10.0.0

Dry running finishes the update successfully

<details>

<pre>
cargo run -- --verbose
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/topgrade --verbose`
 2022-10-25T23:00:42.725Z DEBUG topgrade::config > Configuration at /Users/nagybotond/.config/topgrade.toml
 2022-10-25T23:00:42.727Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: Some([Mas, Vim, System, GithubCliExtensions, Containers, Pip3, Node, Gem, GitRepos]), ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: Some(true), yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: Some(true), notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, autoremove: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }) }
 2022-10-25T23:00:42.728Z DEBUG topgrade         > Version: 10.0.0
 2022-10-25T23:00:42.728Z DEBUG topgrade         > OS: aarch64-apple-darwin
 2022-10-25T23:00:42.728Z DEBUG topgrade         > Args { inner: ["target/debug/topgrade", "--verbose"] }
 2022-10-25T23:00:42.728Z DEBUG topgrade         > Binary path: Ok("/Users/nagybotond/dev/forks/topgrade/target/debug/topgrade")
 2022-10-25T23:00:42.728Z DEBUG topgrade         > Self Update: false
 2022-10-25T23:00:42.729Z DEBUG topgrade::utils  > Detected "/opt/homebrew/bin/git" as "git"
 2022-10-25T23:00:42.729Z DEBUG topgrade::utils  > Cannot find "doas"
 2022-10-25T23:00:42.729Z DEBUG topgrade::utils  > Detected "/usr/bin/sudo" as "sudo"
 2022-10-25T23:00:42.730Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2022-10-25T23:00:42.730Z DEBUG topgrade::utils  > Cannot find "powershell"
 2022-10-25T23:00:42.730Z DEBUG topgrade::runner > Step "Brew (ARM)"
 2022-10-25T23:00:42.730Z DEBUG topgrade::utils  > Detected "/opt/homebrew/bin/brew" as "/opt/homebrew/bin/brew"

―― 02:00:42 - Brew ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-10-25T23:00:42.731Z DEBUG topgrade::executor > Running "/opt/homebrew/bin/brew" "update"
Already up-to-date.
 2022-10-25T23:00:43.983Z DEBUG topgrade::executor > Running "/opt/homebrew/bin/brew" "upgrade" "--ignore-pinned" "--formula"
 2022-10-25T23:00:45.166Z DEBUG topgrade::executor > Running "/opt/homebrew/bin/brew" "cleanup"
 2022-10-25T23:00:54.580Z DEBUG topgrade::runner   > Step "Brew (Intel)"
 2022-10-25T23:00:54.580Z DEBUG topgrade::runner   > Step "Brew"
 2022-10-25T23:00:54.580Z DEBUG topgrade::utils    > Detected "/opt/homebrew/bin/brew" as "brew"
 2022-10-25T23:00:54.580Z DEBUG topgrade::runner   > Step "Brew Cask (ARM)"
 2022-10-25T23:00:54.580Z DEBUG topgrade::utils    > Detected "/opt/homebrew/bin/brew" as "/opt/homebrew/bin/brew"

―― 02:00:54 - Brew - Cask ――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-10-25T23:00:55.242Z DEBUG topgrade::executor > Running "/opt/homebrew/bin/brew" "upgrade" "--cask"
 2022-10-25T23:00:55.938Z DEBUG topgrade::executor > Running "/opt/homebrew/bin/brew" "cleanup"
 2022-10-25T23:01:05.550Z DEBUG topgrade::runner   > Step "Brew Cask (Intel)"
 2022-10-25T23:01:05.550Z DEBUG topgrade::runner   > Step "Brew Cask"
 2022-10-25T23:01:05.550Z DEBUG topgrade::utils    > Detected "/opt/homebrew/bin/brew" as "brew"
 2022-10-25T23:01:05.550Z DEBUG topgrade::runner   > Step "MacPorts"
 2022-10-25T23:01:05.551Z DEBUG topgrade::runner   > Step "yadm"
 2022-10-25T23:01:05.551Z DEBUG topgrade::runner   > Step "nix"
 2022-10-25T23:01:05.551Z DEBUG topgrade::runner   > Step "guix"
 2022-10-25T23:01:05.551Z DEBUG topgrade::runner   > Step "home-manager"
 2022-10-25T23:01:05.551Z DEBUG topgrade::runner   > Step "asdf"
 2022-10-25T23:01:05.552Z DEBUG topgrade::runner   > Step "pkgin"
 2022-10-25T23:01:05.552Z DEBUG topgrade::runner   > Step "bun"
 2022-10-25T23:01:05.552Z DEBUG topgrade::utils    > Detected "/Users/nagybotond/.bun/bin/bun" as "bun"

―― 02:01:05 - Bun ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-10-25T23:01:05.552Z DEBUG topgrade::executor > Running "/Users/nagybotond/.bun/bin/bun" "upgrade"
Congrats! You're already on the latest version of bun (which is v0.2.1)
 2022-10-25T23:01:05.987Z DEBUG topgrade::utils    > Path "/Users/nagybotond/.config/emacs" doesn't exist
 2022-10-25T23:01:05.987Z DEBUG topgrade::utils    > Path "/Users/nagybotond/.emacs.d" doesn't exist
 2022-10-25T23:01:05.987Z DEBUG topgrade::steps::git > /Users/nagybotond/.doom.d does not exists
 2022-10-25T23:01:05.987Z DEBUG topgrade::steps::git > /Users/nagybotond/.ideavimrc does not exists
 2022-10-25T23:01:05.987Z DEBUG topgrade::steps::git > /Users/nagybotond/.intellimacs does not exists
 2022-10-25T23:01:05.987Z DEBUG topgrade::steps::git > /Users/nagybotond/.dotfiles/zshrc is a file. Checking /Users/nagybotond/.dotfiles
 2022-10-25T23:01:05.987Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.dotfiles is a git repository
 2022-10-25T23:01:05.998Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(0)), stdout: "/Users/nagybotond/.dotfiles\n", stderr: "" }
 2022-10-25T23:01:05.998Z DEBUG topgrade::steps::git > /Users/nagybotond/.tmux does not exists
 2022-10-25T23:01:05.998Z DEBUG topgrade::steps::git > /Users/nagybotond/.config/fish does not exists
 2022-10-25T23:01:05.999Z DEBUG topgrade::steps::git > /Users/nagybotond/Library/Application Support/openbox does not exists
 2022-10-25T23:01:05.999Z DEBUG topgrade::steps::git > /Users/nagybotond/Library/Application Support/bspwm does not exists
 2022-10-25T23:01:05.999Z DEBUG topgrade::steps::git > /Users/nagybotond/Library/Application Support/i3 does not exists
 2022-10-25T23:01:05.999Z DEBUG topgrade::steps::git > /Users/nagybotond/Library/Application Support/sway does not exists
 2022-10-25T23:01:05.999Z DEBUG topgrade::runner     > Step "zr"
 2022-10-25T23:01:05.999Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.000Z DEBUG topgrade::runner     > Step "antibody"
 2022-10-25T23:01:06.000Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.001Z DEBUG topgrade::runner     > Step "antigen"
 2022-10-25T23:01:06.001Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.001Z DEBUG topgrade::utils      > Path "/Users/nagybotond/.zshrc" exists
 2022-10-25T23:01:06.001Z DEBUG topgrade::runner     > Step "zgenom"
 2022-10-25T23:01:06.001Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.001Z DEBUG topgrade::utils      > Path "/Users/nagybotond/.zshrc" exists
 2022-10-25T23:01:06.001Z DEBUG topgrade::runner     > Step "zplug"
 2022-10-25T23:01:06.001Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.001Z DEBUG topgrade::utils      > Path "/Users/nagybotond/.zshrc" exists
 2022-10-25T23:01:06.002Z DEBUG topgrade::runner     > Step "zinit"
 2022-10-25T23:01:06.002Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.002Z DEBUG topgrade::utils      > Path "/Users/nagybotond/.zshrc" exists
 2022-10-25T23:01:06.002Z DEBUG topgrade::runner     > Step "zi"
 2022-10-25T23:01:06.002Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.002Z DEBUG topgrade::utils      > Path "/Users/nagybotond/.zshrc" exists
 2022-10-25T23:01:06.002Z DEBUG topgrade::runner     > Step "zim"
 2022-10-25T23:01:06.002Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.013Z TRACE topgrade::executor   > Output of "zsh" "-c" "[[ -n ${ZIM_HOME} ]] && print -n ${ZIM_HOME}": Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }
 2022-10-25T23:01:06.013Z DEBUG topgrade::runner     > Step "oh-my-zsh"
 2022-10-25T23:01:06.013Z DEBUG topgrade::utils      > Detected "/bin/zsh" as "zsh"
 2022-10-25T23:01:06.013Z DEBUG topgrade::utils      > Path "/Users/nagybotond/.oh-my-zsh" exists

―― 02:01:06 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-10-25T23:01:06.014Z DEBUG topgrade::steps::zsh > oh-my-zsh custom dir: /Users/nagybotond/.omzcustom/
 2022-10-25T23:01:06.014Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom is a git repository
 2022-10-25T23:01:06.022Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(32768)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2022-10-25T23:01:06.022Z DEBUG topgrade::steps::git > /Users/nagybotond/.dotfiles/omzcustom/aliases.zsh is a file. Checking /Users/nagybotond/.dotfiles/omzcustom
 2022-10-25T23:01:06.022Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.dotfiles/omzcustom is a git repository
 2022-10-25T23:01:06.029Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(0)), stdout: "/Users/nagybotond/.dotfiles\n", stderr: "" }
 2022-10-25T23:01:06.029Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom/plugins is a git repository
 2022-10-25T23:01:06.035Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(32768)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2022-10-25T23:01:06.035Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom/plugins/evalcache is a git repository
 2022-10-25T23:01:06.040Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(0)), stdout: "/Users/nagybotond/.omzcustom/plugins/evalcache\n", stderr: "" }
 2022-10-25T23:01:06.040Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom/plugins/zsh-autosuggestions is a git repository
 2022-10-25T23:01:06.045Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(0)), stdout: "/Users/nagybotond/.omzcustom/plugins/zsh-autosuggestions\n", stderr: "" }
 2022-10-25T23:01:06.045Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom/plugins/msfvenom is a git repository
 2022-10-25T23:01:06.049Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(0)), stdout: "/Users/nagybotond/.omzcustom/plugins/msfvenom\n", stderr: "" }
 2022-10-25T23:01:06.049Z DEBUG topgrade::steps::git > /Users/nagybotond/.dotfiles/omzcustom/environment.zsh is a file. Checking /Users/nagybotond/.dotfiles/omzcustom
 2022-10-25T23:01:06.049Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.dotfiles/omzcustom is a git repository
 2022-10-25T23:01:06.053Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(0)), stdout: "/Users/nagybotond/.dotfiles\n", stderr: "" }
 2022-10-25T23:01:06.053Z DEBUG topgrade::steps::git > /Users/nagybotond/.omzcustom/example.zsh is a file. Checking /Users/nagybotond/.omzcustom
 2022-10-25T23:01:06.053Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom is a git repository
 2022-10-25T23:01:06.056Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(32768)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2022-10-25T23:01:06.057Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom/zcompdump is a git repository
 2022-10-25T23:01:06.060Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(32768)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2022-10-25T23:01:06.061Z DEBUG topgrade::steps::git > /Users/nagybotond/.dotfiles/omzcustom/path.zsh is a file. Checking /Users/nagybotond/.dotfiles/omzcustom
 2022-10-25T23:01:06.061Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.dotfiles/omzcustom is a git repository
 2022-10-25T23:01:06.065Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(0)), stdout: "/Users/nagybotond/.dotfiles\n", stderr: "" }
 2022-10-25T23:01:06.065Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom/themes is a git repository
 2022-10-25T23:01:06.068Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(32768)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2022-10-25T23:01:06.068Z DEBUG topgrade::steps::git > /Users/nagybotond/.omzcustom/themes/example.zsh-theme is a file. Checking /Users/nagybotond/.omzcustom/themes
 2022-10-25T23:01:06.068Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.omzcustom/themes is a git repository
 2022-10-25T23:01:06.071Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(32768)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2022-10-25T23:01:06.071Z DEBUG topgrade::steps::git > /Users/nagybotond/.dotfiles/omzcustom/themes/apple_custom.zsh-theme is a file. Checking /Users/nagybotond/.dotfiles/omzcustom/themes
 2022-10-25T23:01:06.071Z DEBUG topgrade::steps::git > Checking if /Users/nagybotond/.dotfiles/omzcustom/themes is a git repository
 2022-10-25T23:01:06.074Z TRACE topgrade::executor   > Output of "/opt/homebrew/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(unix_wait_status(0)), stdout: "/Users/nagybotond/.dotfiles\n", stderr: "" }
[src/steps/git.rs:309] "{:#?}" = "{:#?}"
[src/steps/git.rs:309] &self.repositories = {
    "/Users/nagybotond/.omzcustom/plugins/evalcache",
    "/Users/nagybotond/.omzcustom/plugins/msfvenom",
    "/Users/nagybotond/.dotfiles",
    "/Users/nagybotond/.omzcustom/plugins/zsh-autosuggestions",
}
[src/steps/git.rs:310] "{:#?}" = "{:#?}"
[src/steps/git.rs:310] path = "/Users/nagybotond/.oh-my-zsh"
thread 'main' panicked at 'assertion failed: _removed', src/steps/git.rs:311:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/panicking.rs:115:5
   3: topgrade::steps::git::Repositories::remove
             at ./src/steps/git.rs:311:9
   4: topgrade::steps::zsh::run_oh_my_zsh
             at ./src/steps/zsh.rs:161:5
   5: topgrade::run::{{closure}}
             at ./src/main.rs:289:53
   6: topgrade::runner::Runner::execute
             at ./src/runner.rs:37:19
   7: topgrade::run
             at ./src/main.rs:289:9
   8: topgrade::main
             at ./src/main.rs:489:11
   9: core::ops::function::FnOnce::call_once
             at /rustc/758f19645b8ebce61ea52d1f6672fd057bc8dbee/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre>
</details>

It seems to me that even though the update happens for oh-my-zsh, for some reason it's not present in topgrade::steps::git::repositories, so the `remove` call on `repositories returns false:

```rust
#[cfg(unix)]
    pub fn remove(&mut self, path: &str) {
        let _removed = self.repositories.remove(path);
        debug_assert!(_removed);
    }
```

**Comment by westernwontons** [comment]
Closing in favor of #71

**Comment by DottoDev** [comment]
Is this issue fixed for you by PR #71 ?

**Comment by westernwontons** [comment]
@DottoDev Yes, that PR fixes it

**Comment by DottoDev** [comment]
Great
